from . import scrap_collection
from . import scrap_desktop
from . import scrap_category
from . import scrap_selling
from . import scrapapp_product_category
from . import scrapapp_product_product
from . import scrap_inventory
from . import ScrapItems
from . import res_config_settings
